# Data reduction to work

In [1]:
import os
import pandas as pd

In [2]:
# Constants
DATA_DIR = "data"
FULL_DATA_DIR = os.path.join("data", "full")


COMPANIES_FILE = os.path.join(FULL_DATA_DIR, "empresas.csv")
PARTNERS_FILE = os.path.join(FULL_DATA_DIR, "socios.csv")
CNAES_FILE = os.path.join(FULL_DATA_DIR, "cnaes_secundarios.csv")
EDUCATION_CODE = 8500000
CNAE_OFFSET = 100000

EDU_COMPANIES_FILE = os.path.join(DATA_DIR, "edu_empresas.csv")
EDU_PARTNERS_FILE = os.path.join(DATA_DIR, "edu_socios.csv")

In [3]:
chk_size = 100000
iter_companies = pd.read_csv(COMPANIES_FILE, iterator=True, chunksize=chk_size)
index = 0
for chunk in iter_companies:
    edu_chunk = chunk[(chunk['cnae_fiscal']%EDUCATION_CODE) < (CNAE_OFFSET-1)] #CNAE starting with 85
    edu_chunk.to_csv(EDU_COMPANIES_FILE, mode='a', header= True if index == 0 else False)
    index = index + 1
    if index%50 == 0:
        print("chunk number:" , index, "Lines processed:", index*chk_size)
print("Total chunks processed:", index)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (23,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,22,23,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,22,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,25,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,22,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23,25,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (23,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

chunk number: 50 Lines processed: 5000000

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (22,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,23,25,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,23,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,23,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,23,25,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (23,25,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,23,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,23,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23,27,28,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,22,25,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,22,25,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (25,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,25,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23,25,26,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (22,23,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (23,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

chunk number: 100 Lines processed: 10000000

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (22,23,25,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (3,7,9,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (25,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (22,23,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,22,23,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,22,23,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

chunk number: 150 Lines processed: 15000000

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,22,23,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,23,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (23,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

chunk number: 200 Lines processed: 20000000

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (22,23,25,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (22,23,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,22,23,25,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,22,23,25,27,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

chunk number: 250 Lines processed: 25000000

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,23,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

chunk number: 300 Lines processed: 30000000
chunk number: 350 Lines processed: 35000000

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23,27,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

chunk number: 400 Lines processed: 40000000

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (7,9,23,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,23,27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Total chunks processed: 416

In [5]:
df_educompanies = pd.read_csv(EDU_COMPANIES_FILE, index_col=0)
df_educompanies.head(10)

33661084

,cnpj,matriz_filial,razao_social,nome_fantasia,situacao,data_situacao,motivo_situacao,nm_cidade_exterior,cod_pais,nome_pais,...,email,qualif_resp,capital_social,porte,opc_simples,data_opc_simples,data_exc_simples,opc_mei,sit_especial,data_sit_especial
7732,39000109,1,MISSAO RAMA DO BRASIL,NaN,2,20041224,0,NaN,NaN,NaN,...,NaN,16,0.0,5,0,NaN,NaN,N,NaN,NaN
7754,52000168,1,RECREACAO ESCOLA INFANTIL TREVINHO VERDE S/C LTDA,NaN,8,20081231,71,NaN,NaN,NaN,...,NaN,28,0.0,5,0,NaN,NaN,N,NaN,NaN
7764,62000101,1,CENTRO DE RECREACAO INFANTIL GRILINHO S/C.LTDA.,NaN,8,19980731,1,NaN,NaN,NaN,...,NaN,28,0.0,5,0,NaN,NaN,N,NaN,NaN
7768,66000181,1,ASSOCIACAO BENEFICENTE LUZ DE UM NOVO DIA,NaN,2,20081231,0,NaN,NaN,NaN,...,CRESCENDOCOMALEGRIA@GMAIL.COM,16,0.0,5,0,NaN,NaN,N,NaN,NaN
7818,104000287,2,INSTITUTO GRANDE VITORIA,C.E.I. ''GRANDE VITORIA'' - UNIDADE 1,4,20190321,63,NaN,NaN,NaN,...,fisconta@terra.com.br,16,0.0,5,0,NaN,NaN,NaN,NaN,NaN
7819,104000368,2,INSTITUTO GRANDE VITORIA,C.E.I. 'ALBERTINA DE SOUSA' - UNIDADE 2,4,20190321,63,NaN,NaN,NaN,...,FISCONTA@TERRA.COM.BR,16,0.0,5,0,NaN,NaN,NaN,NaN,NaN
7824,110000153,1,LEONARDO & MODICA LTDA,STEP DATA,4,20190321,63,NaN,NaN,NaN,...,NaN,49,0.0,5,0,NaN,NaN,N,NaN,NaN
7828,113000278,2,ASSOCIACAO GRUPO DE MAES SOLIDARIAS BEM VIVER,CENTRO DE EDUCACAO INFANTIL 15 DE AGOSTO,4,20180906,63,NaN,NaN,NaN,...,cris.somater@hotmail.com,16,0.0,5,0,NaN,NaN,NaN,NaN,NaN
7829,113000359,2,ASSOCIACAO GRUPO DE MAES SOLIDARIAS BEM VIVER,CENTRO DE EDUCAO INFANTIL JULIA NASCIMENTO,4,20180906,63,NaN,NaN,NaN,...,jucelene@kajcontabilidade.com.br,16,0.0,5,0,NaN,NaN,NaN,NaN,NaN
7839,122000188,1,TAUMATURGO E ALKIMIM RECREACAO INFANTIL S/C LTDA,NaN,8,20081231,71,NaN,NaN,NaN,...,NaN,49,0.0,5,0,NaN,NaN,N,NaN,NaN

In [6]:
print(df_educompanies.shape)

(885818, 38)

In [4]:
companies.columns.values

array(['cnpj', 'matriz_filial', 'razao_social', 'nome_fantasia',
       'situacao', 'data_situacao', 'motivo_situacao',
       'nm_cidade_exterior', 'cod_pais', 'nome_pais', 'cod_nat_juridica',
       'data_inicio_ativ', 'cnae_fiscal', 'tipo_logradouro', 'logradouro',
       'numero', 'complemento', 'bairro', 'cep', 'uf', 'cod_municipio',
       'municipio', 'ddd_1', 'telefone_1', 'ddd_2', 'telefone_2',
       'ddd_fax', 'num_fax', 'email', 'qualif_resp', 'capital_social',
       'porte', 'opc_simples', 'data_opc_simples', 'data_exc_simples',
       'opc_mei', 'sit_especial', 'data_sit_especial'], dtype=object)

In [9]:
# Selecting EDU partners
iter_partners = pd.read_csv(PARTNERS_FILE, iterator=True, chunksize=chk_size)
index = 0
edu_cnpjs = df_educompanies.cnpj
for chunk in iter_partners:
    edu_chunk = chunk[chunk['cnpj'].isin(edu_cnpjs)] #CNAE starting with 85
    edu_chunk.to_csv(EDU_PARTNERS_FILE, mode='a', header= True if index == 0 else False)
    index = index + 1
    if index%10 == 0:
        print("chunk number:" , index, "Lines processed:", index*chk_size)
print("Total chunks processed:", index)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

chunk number: 10 Lines processed: 1000000
chunk number: 20 Lines processed: 2000000
chunk number: 30 Lines processed: 3000000
chunk number: 40 Lines processed: 4000000
chunk number: 50 Lines processed: 5000000
chunk number: 60 Lines processed: 6000000
chunk number: 70 Lines processed: 7000000
chunk number: 80 Lines processed: 8000000
chunk number: 90 Lines processed: 9000000
chunk number: 100 Lines processed: 10000000
chunk number: 110 Lines processed: 11000000
chunk number: 120 Lines processed: 12000000
chunk number: 130 Lines processed: 13000000
chunk number: 140 Lines processed: 14000000
chunk number: 150 Lines processed: 15000000
chunk number: 160 Lines processed: 16000000
chunk number: 170 Lines processed: 17000000
chunk number: 180 Lines processed: 18000000
chunk number: 190 Lines processed: 19000000
chunk number: 200 Lines processed: 20000000
chunk number: 210 Lines processed: 21000000
chunk number: 220 Lines processed: 22000000
chunk number: 230 Lines processed: 23000000
chunk number: 240 Lines processed: 24000000
chunk number: 250 Lines processed: 25000000
chunk number: 260 Lines processed: 26000000
Total chunks processed: 262

In [10]:
df_edupartners = pd.read_csv(EDU_PARTNERS_FILE, index_col=0)
print(df_edupartners.shape)
df_edupartners.head(10)

(610286, 12)

,cnpj,tipo_socio,nome_socio,cnpj_cpf_socio,cod_qualificacao,perc_capital,data_entrada,cod_pais_ext,nome_pais_ext,cpf_repres,nome_repres,cod_qualif_repres
353826,39000109,2,CARLOS ROBERTO PAZ WELLS,***835158**,16,0.0,20050912,249.0,ESTADOS UNIDOS,NaN,NaN,0
353860,62000101,2,ROMILDA FARIA DE OLIVEIRA,***901288**,28,0.0,19940617,249.0,ESTADOS UNIDOS,NaN,NaN,0
353861,62000101,2,MARCOS CESAR DE OLIVEIRA,***381868**,28,0.0,19940617,249.0,ESTADOS UNIDOS,NaN,NaN,0
353866,66000181,2,JOSE PELEGATTI NETO,***955548**,16,0.0,20181122,249.0,ESTADOS UNIDOS,NaN,NaN,0
353921,104000287,2,ANDREIA RIBEIRO DOS SANTOS,***217858**,16,0.0,20120731,573.0,Países Baixos (Holanda),NaN,NaN,0
353922,104000368,2,ANDREIA RIBEIRO DOS SANTOS,***217858**,16,0.0,20120731,573.0,Países Baixos (Holanda),NaN,NaN,0
353930,113000278,2,KARINA FERNANDES DE SOUZA,***165538**,16,0.0,20100119,386.0,ITALIA,NaN,NaN,0
353931,113000359,2,KARINA FERNANDES DE SOUZA,***165538**,16,0.0,20100119,493.0,MEXICO,NaN,NaN,0
353948,130000124,2,MARCIO ROSA DE ARAUJO,***958318**,16,0.0,20160502,249.0,ESTADOS UNIDOS,NaN,NaN,0
353955,138000271,2,REGILENE GOMES RODRIGUES,***200518**,16,0.0,20130718,137.0,"CAYMAN,ILHAS",NaN,NaN,0

In [6]:
pd_partners.columns.values

array(['cnpj', 'tipo_socio', 'nome_socio', 'cnpj_cpf_socio',
       'cod_qualificacao', 'perc_capital', 'data_entrada', 'cod_pais_ext',
       'nome_pais_ext', 'cpf_repres', 'nome_repres', 'cod_qualif_repres'],
      dtype=object)

In [ ]:
df_cnaes = pd.read_csv()